arch:
  - amd64
  - arm64
language: python
python:
  - "3.8"
git:
  depth: false
services:
  - docker
before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - pip install -r requirements-dev.txt
script: tools/push --no-manifest-list

jobs:
  include:
    - stage: test
      name: Build and push images

    - stage: Create and push manifest lists (image bundle)
      script: tools/push --manifest-list

    - stage: Test common cases
      script: tools/test
